print("\t\tData Diri Mahasiswa")
print("\t\t-------------------\n")
nim=input("Masukkan NIM Anda\t:")
nama=input("Masukkan Nama Anda\t:")
jurusan=input("Jurusan anda\t\t:")
alamat=input("Alamat anda\t\t:")
print("\n")
print("Hasil Cetak Data Mahasiswa")
print("==========================")
print("Nim\t:", nim)
print("Nama\t:", nama)
print("Jurusan\t:", jurusan)
print("Alamat\t:", alamat)