print("\t\tData Diri Mahasiswa")
print("\t\t-------------------\n")
nim=input("Masukkan NIM Anda\t:")
nama=input("Masukkan Nama Anda\t:")
jurusan=input("Jurusan anda\t\t:")
alamat=input("Alamat anda\t\t:")
print("\n")
print("Hasil Cetak Data Mahasiswa")
print("==========================")
print("Nim\t:"+str(nim))
print("Nama\t:"+str(nama))
print("Jurusan\t:"+str(jurusan))
print("Alamat\t:"+str(alamat))