#Senin 19 September 2022
print("\t\t----BSI Optik----\n")
id_pelanggan=input("Input ID Pelanggan\t:")
nama_customer=input("Masukkan nama customer\t:")
lensa_r=float(input("Lensa Kanan\t\t:"))
lensa_l=float(input("Lensa Kiri\t\t:"))
harga=int(input("Harga\t\t\t:"))
print("\n")
print("----Struk pembelian kacamata----")
print("ID Pelanggan\t:" +str(id_pelanggan))
print("Nama customer\t:" +str(nama_customer))
print("Lensa Kanan\t:" +str(lensa_r))
print("Lensa Kiri\t:" +str(lensa_l))
print("Harga kacamata\t:" +str(harga))
